language: python
python:
- '2.7'
- '3.8'
- pypy
script: python test.py
deploy:
  provider: pypi
  user: __token__
  password:
    secure: IGmFMwu4qTV6Kg7B36Jw2Bg0yYHS7pe1x5xO7XAjKZd+FX+CKQry/sU/fDsB5EVOkMbBSFnAz8vc4tODZ4A8kdZTAfMTD9+XaTp9Fb/+5kcwNd1W2tACnYMvQ25kDMc9fIJB+VI/N7PUXZZYvBZUK7Gw4bdeujyB0LpGRphzSBOBzJ5EYfe4R7/AuFwftFjpkHZWCSYwbtb2UqpTkVaZA4pV7ydRtSNQT7ryeMnuuGHwfJsf+YlOF1CovDuvyHVCCua3B/HZ72KYMumtzexOkS8NLCyaYk4n2GQuozAQGJD+oM0auKlS7a9nDQUpWjm2x2FHOopiyA8GMPRKEPjLF8sUZPTygE71zR7v95xu6sgxcNC7v5PAWdOVreOmCnVWKmOyyvKx5yDvh6op6L8YemfT9nEE3WiGvsOrrFpDbhaXLp6O1EMnyBvEqFQC/O9WW8xy8lZ9O2Sczd6cl9maeMKOyMy/4/DSSDFgwmSAV3xwzYP9lj08fO3/nAd6UxD7IptWdjJVJhscP5pFOmWSaHxwfsV4NTtIKQYAAmQ58pnzIIwpibBkD1cGQyAwLGxDhwsbK7jVRTvtUkAsaQKaiZkO4GDXnzERprT7ep4ozrkTqkcWYyTeXGhONuOrfNJdSWrw3QLZQtOZlFzHWJrw6HiWllLsr9nFRwqm9imoBIQ=
  on:
    python: 3.8
    tags: true
    branch: master
